services:
  api:
    build: .
    container_name: eficiencia_energetica_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
